ALTER TABLE "Negociacion" ALTER COLUMN "precioUnitario" TYPE DECIMAL(15,2);
ALTER TABLE "Negociacion" ALTER COLUMN "costoFlete" TYPE DECIMAL(15,2);
ALTER TABLE "Factura" ALTER COLUMN "subtotal" TYPE DECIMAL(15,2);
ALTER TABLE "Factura" ALTER COLUMN "costoFlete" TYPE DECIMAL(15,2);
ALTER TABLE "Factura" ALTER COLUMN "comisionPlataforma" TYPE DECIMAL(15,2);
ALTER TABLE "Factura" ALTER COLUMN "total" TYPE DECIMAL(15,2);